name: RAS CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend:
    name: Backend (Django) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        run: |
          python manage.py migrate

      - name: Run backend tests
        run: |
          python manage.py test

      - name: Lint backend code
        run: |
          pip install flake8
          flake8 .

  frontend:
    name: Frontend (React) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RAS UI/RAS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install

      - name: Lint frontend code
        run: npx eslint . || true

      - name: Run frontend tests
        run: npm test -- --watchAll=false

      - name: Build frontend
        run: npm run build
